language: python
python:
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install lupyne[server]
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

branches:
  only:
  - main

script: pytest
