language: python
python:
  - 3.8
services:
  - docker
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  - docker pull azdb/lupyne:version2
  - docker run azdb/lupyne:version2 /bin/sh -c "pytest"

branches:
  only:
  - main

script: pytest
