language: python
python:
  - 3.8
services:
  - docker
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  - docker pull azdb/lupyne:version2
  - docker run azdb/lupyne:version2 /bin/sh -c "git clone -b currim_faiz_dev https://github.com/cs4583Fall2020/hw3-python-currim19.git .; export PYTHONPATH=$PYTHONPATH:$(pwd); pytest"

branches:
  only:
  - main

script: pytest
